title: Witch Tails
email: raphexion@gmail.com
description: >-
  The Elixir ecosystem has numerous small but important libraries.
  Some of these are written by a single person that saw a problem and found a solution.
  Unfortunately, sometimes the maintainer doesn't have the time to keep the library up-to-date.

  Instead of having a 1-to-1 relationship between a library and a maintainer, we provide a N-to-M relationship.
  Where we in the Witch Tails group (N) help to maintain multiple small libraries (M).
  As a group we can support one another by taking over tasks when someone is busy (life happens).

  If you have written a library or know of a library that needs some extra love, please let us know.
baseurl: "" # the subpath of your site, e.g. /blog
url: "witchtails.github.io"
twitter_username: witchtails
github_username: witchtails

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
